spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          timeout: 10
          uri: https://github.com/rutujadattajadhav/configserverrepository
          clone-on-start: true
         # cloneOnStartShallow: true
          searchPaths: 'services/{application}'
          username: rutujadattajadhav@gmail.com
          password: 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
          #default-label: "*"  # default Git branch
    #request-connect-timeout: 5000
    #request-read-timeout: 15000
#  resttemplate:
#    timeout:
#      read: 10000  # Read timeout in milliseconds
#      connect: 5000  # Connection timeout in milliseconds
#  webclient:
#    timeout:
#      read: 10000
#      connect: 5000
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka
server:
  port: 8086
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: DEBUG
    org:
      springframework:
        cloud:
          config:
            server: DEBUG
